<?php
/**
 * @category  Crankycyclops
 * @package   Crankycyclops_Newsletter
 * @author    James Colannino
 * @copyright Copyright (c) 2019 James Colannino
 * @license   https://opensource.org/licenses/OSL-3.0 OSL v3
 */
?>

<script type="text/x-magento-init">
	{
		".block.newsletter": {
			"newsletterAjax": {"loadingImgUrl": "<?= $this->getViewFileUrl('Crankycyclops_Newsletter::images/loading-subscription.gif'); ?>"}
		}
	}
</script>

